#freemarker通过BootstrapConfig类转换到congif/freemarker/freemarkerConfig.yml中
spring:
  profiles:
    active: prod
  datasource:
    url: jdbc:mysql://localhost:3306/school
    username: root
    password: ENC(2GYKBvwwUmQFbqOAlSwUDQ==)
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    #最大连接池数量
    maxActive: 20480
    #初始化时建立物理连接的个数
    initialSize: 1
    #获取连接时最大等待时间，单位毫秒。
    maxWait: 60000
    #最小连接池数量
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    #用来检测连接是否有效的sql
    validationQuery: select 'x'
    #建议配置为true，不影响性能，并且保证安全性。
    testWhileIdle: true
    #申请连接时执行validationQuery检测连接是否有效
    testOnBorrow: false
    testOnReturn: false
    #是否缓存preparedStatement，也就是PSCache
    poolPreparedStatements: false
    maxOpenPreparedStatements: 20
  resources:
    #静态资源加载路径根目录
    #src="js/jquery-3.3.1.min.js"引入的则是/webapp/js/jquery-3.3.1.min.js
    static-locations:
     - classpath:/webapp/
## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:root/code/mapper/impl/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: root.code.pojo  # 注意：对应实体类的路径

logging:
  config: classpath:config/log/logConfig.xml
jasypt:
  encryptor:
    password: password