spring:
 freemarker:
  # Whether to enable MVC view resolution for this technology.
  #是否启用该技术的MVC视图解析，默认：true
  #enabled: true
  # Whether to enable template caching.
  #是否开启缓存
  cache: false
  # Well-known FreeMarker keys which are passed to FreeMarker's Configuration.
  settings:
   locale: zh_CN
   output_encoding: UTF-8
   url_escaping_charset: utf_8
   number_format: !!str 0.##
   datetime_format: yyyy-MM-dd HH:mm:ss
   date_format: yyyy-MM-dd
  # Prefix that gets prepended to view names when building a URL.
  #在构建URL时可以预览查看名称的前缀。
  prefix: ~
  # Suffix that gets appended to view names when building a URL.
  #在构建URL时附加到视图名称的后缀
  suffix: .ftl
  # Comma-separated list of template paths.
  # 模板路径(可用逗号分割或用数组形式)。
  template-loader-path:
   - classpath:/webapp/templates/